# Generated by Django 6.0.3 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]